### ISSUE TITLE
uglifyjs out of date

### ISSUE THREAD

**Issue by yomed** [lasso-js/lasso-minify-js#1]
Recently I've been running into issues where the minifier is far too aggressive, and I noticed that uglifyjs is severely out of date. Any objections to bumping it?

**Comment by philidem** [comment]
I would appreciate an upgrade to this dependency or any other dependency as long as it doesn't introduce any breaking changes (I'm guessing uglifyjs upgrade will be fairly straightforward).

**Comment by patrick-steele-idem** [comment]
I have no objections to bumping the version. We currently lack in-browser tests so please do some sanity testing. Thanks for looking into this!
